# Generated by Django 3.2.8 on 2021-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0002_rename_author_messages_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='author_username',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(max_length=99),
        ),
    ]
